name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Project
        run: ./gradlew assemble

      - name: UnitTest
        run: ./gradlew test --stacktrace

      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew connectedCheck --stacktrace
          api: 25
          tag: default
          abi: x86

      - name: Check Lint
        run: ./gradlew lint
